### ISSUE TITLE
jake app:assets

### ISSUE THREAD

**Issue by ButuzGOL** [alessioalex/ClientManager#3]
run jake app:assets
jake aborted.
Error: Error: ENOENT, no such file or directory '/.../ClientManager/lib/../public/js/App.js'

at build (/home/butuzgol/Desktop/backbone/ClientManager/node_modules/requirejs/bin/r.js:14167:23)
    at requirejs.optimize.runBuild (/home/butuzgol/Desktop/backbone/ClientManager/node_modules/requirejs/bin/r.js:15359:30)
    at Object.context.execCb (/home/butuzgol/Desktop/backbone/ClientManager/node_modules/requirejs/bin/r.js:1774:33)
    at Object.Module.check (/home/butuzgol/Desktop/backbone/ClientManager/node_modules/requirejs/bin/r.js:1084:51)
    at Object.Module.enable (/home/butuzgol/Desktop/backbone/ClientManager/node_modules/requirejs/bin/r.js:1325:22)
    at Object.Module.init (/home/butuzgol/Desktop/backbone/ClientManager/node_modules/requirejs/bin/r.js:983:26)
    at Object.context.require (/home/butuzgol/Desktop/backbone/ClientManager/node_modules/requirejs/bin/r.js:1580:28)
    at requirejs (/home/butuzgol/Desktop/backbone/ClientManager/node_modules/requirejs/bin/r.js:1858:24)
    at Function.requirejs.optimize (/home/butuzgol/Desktop/backbone/ClientManager/node_modules/requirejs/bin/r.js:15369:13)
    at assetBuilder (/home/butuzgol/Desktop/backbone/ClientManager/lib/assetBuilder.js:38:13)

**Comment by ButuzGOL** [comment]
Have to add this in assetBuilder.js
'App'              : 'app',
'Router'          : 'router',
